version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: "Yarn install"
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Log in to npm"
          command: yarn npm-login
      - run:
          name: "Deploy image to npm"
          command: npm publish

  test-version:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: Run version test
          command: yarn test:version

workflows:
  version: 2

  build:
    jobs:
      - test-version
      - build:
          requires:
            - test-version
          filters:
            branches:
              only:
                - master
