version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: "Yarn install"
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Set up npm auth token"
          command: echo //registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc
      - run:
          name: "Deploy image to npm"
          command: npm publish

  test:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2

  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
